apiVersion: v1
kind: Pod
metadata:
  name: testserver
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: testserver
    image: andygrunwald/simple-webserver
    ports:
      - containerPort: 8082